export const COUNTRY_NAMES: Record<string, string> = {
  "AF": "Afg'oniston",
  "AL": "Albaniya",
  "DZ": "Jazoir",
  "AD": "Andorra",
  "AO": "Angola",
  "AG": "Antigua va Barbuda",
  "AR": "Argentina",
  "AM": "Armaniston",
  "AU": "Avstraliya",
  "AT": "Avstriya",
  "AZ": "Ozarbayjon",
  "BS": "Bagama orollari",
  "BH": "Bahrayn",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belorussiya",
  "BE": "Belgiya",
  "BZ": "Beliz",
  "BJ": "Benin",
  "BT": "Butan",
  "BO": "Boliviya",
  "BA": "Bosniya va Gertsegovina",
  "BW": "Botsvana",
  "BR": "Braziliya",
  "BN": "Bruney",
  "BG": "Bolgariya",
  "BF": "Burkina-Faso",
  "BI": "Burundi",
  "CV": "Kabo-Verde",
  "KH": "Kambodja",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CF": "Markaziy Afrika Respublikasi",
  "TD": "Chad",
  "CL": "Chili",
  "CN": "Xitoy",
  "CO": "Kolumbiya",
  "KM": "Komor orollari",
  "CG": "Kongo",
  "CR": "Kosta-Rika",
  "HR": "Xorvatiya",
  "CU": "Kuba",
  "CY": "Kipr",
  "CZ": "Chexiya",
  "DK": "Daniya",
  "DJ": "Jibuti",
  "DM": "Dominika",
  "DO": "Dominikan Respublikasi",
  "EC": "Ekvador",
  "EG": "Misr",
  "SV": "Salvador",
  "GQ": "Ekvatorial Gvineya",
  "ER": "Eritreya",
  "EE": "Estoniya",
  "SZ": "Esvatini",
  "ET": "Efiopiya",
  "FJ": "Fiji",
  "FI": "Finlyandiya",
  "FR": "Fransiya",
  "GA": "Gabon",
  "GM": "Gambiya",
  "GE": "Gruziya",
  "DE": "Germaniya",
  "GH": "Gana",
  "GR": "Gretsiya",
  "GD": "Grenada",
  "GT": "Gvatemala",
  "GN": "Gvineya",
  "GW": "Gvineya-Bisau",
  "GY": "Gayana",
  "HT": "Gaiti",
  "HN": "Gonduras",
  "HU": "Vengriya",
  "IS": "Islandiya",
  "IN": "Hindiston",
  "ID": "Indoneziya",
  "IR": "Eron",
  "IQ": "Iroq",
  "IE": "Irlandiya",
  "IL": "Isroil",
  "IT": "Italiya",
  "JM": "Yamayka",
  "JP": "Yaponiya",
  "JO": "Iordaniya",
  "KZ": "Qozog'iston",
  "KE": "Keniya",
  "KI": "Kiribati",
  "KW": "Kuvayt",
  "KG": "Qirg'iziston",
  "LA": "Laos",
  "LV": "Latviya",
  "LB": "Livan",
  "LS": "Lesoto",
  "LR": "Liberiya",
  "LY": "Liviya",
  "LI": "Lixtenshteyn",
  "LT": "Litva",
  "LU": "Lyuksemburg",
  "MG": "Madagaskar",
  "MW": "Malavi",
  "MY": "Malayziya",
  "MV": "Maldiv orollari",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall orollari",
  "MR": "Mavritaniya",
  "MU": "Mavrikiy",
  "MX": "Meksika",
  "FM": "Mikroneziya",
  "MD": "Moldova",
  "MC": "Monako",
  "MN": "Mongoliya",
  "ME": "Chernogoriya",
  "MA": "Marokash",
  "MZ": "Mozambik",
  "MM": "Myanma",
  "NA": "Namibiya",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Niderlandiya",
  "NZ": "Yangi Zelandiya",
  "NI": "Nikaragua",
  "NE": "Niger",
  "NG": "Nigeriya",
  "KP": "Shimoliy Koreya",
  "MK": "Shimoliy Makedoniya",
  "NO": "Norvegiya",
  "OM": "Umon",
  "PK": "Pokiston",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua-Yangi Gvineya",
  "PY": "Paragvay",
  "PE": "Peru",
  "PH": "Filippin",
  "PL": "Polsha",
  "PT": "Portugaliya",
  "QA": "Qatar",
  "RO": "Ruminiya",
  "RU": "Rossiya",
  "RW": "Ruanda",
  "KN": "Sent-Kits va Nevis",
  "LC": "Sent-Lyusiya",
  "VC": "Sent-Vinsent va Grenadinlar",
  "WS": "Samoa",
  "SM": "San-Marino",
  "ST": "San-Tome va Prinsipi",
  "SA": "Saudiya Arabistoni",
  "SN": "Senegal",
  "RS": "Serbiya",
  "SC": "Seyshel orollari",
  "SL": "Syerra-Leone",
  "SG": "Singapur",
  "SK": "Slovakiya",
  "SI": "Sloveniya",
  "SB": "Solomon orollari",
  "SO": "Somali",
  "ZA": "Janubiy Afrika",
  "KR": "Janubiy Koreya",
  "SS": "Janubiy Sudan",
  "ES": "Ispaniya",
  "LK": "Shri-Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SE": "Shvetsiya",
  "CH": "Shveytsariya",
  "SY": "Suriya",
  "TW": "Tayvan",
  "TJ": "Tojikiston",
  "TZ": "Tanzaniya",
  "TH": "Tailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad va Tobago",
  "TN": "Tunis",
  "TR": "Turkiya",
  "TM": "Turkmaniston",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraina",
  "AE": "Birlashgan Arab Amirliklari (BAA)",
  "GB": "Buyuk Britaniya",
  "US": "Amerika Qo'shma Shtatlari (AQSH)",
  "UY": "Urugvay",
  "UZ": "O'zbekiston",
  "VU": "Vanuatu",
  "VA": "Vatikan",
  "VE": "Venesuela",
  "VN": "Vyetnam",
  "YE": "Yaman",
  "ZM": "Zambiya",
  "ZW": "Zimbabve"
};

export function getCountryFullName(code: string | null | undefined): string {
  if (!code) return '-';
  const cleanCode = code.trim().toUpperCase();
  if (COUNTRY_NAMES[cleanCode]) {
    return COUNTRY_NAMES[cleanCode];
  }
  return code;
}
